# Generated by Django 4.2.26 on 2025-11-19 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format: '+262692123456' ou '0692123456'", regex='^\\+?262\\d{9}$|^0\\d{9}$')], verbose_name='Téléphone')),
                ('carte_identite', models.CharField(blank=True, help_text="Numéro de carte d'identité, passeport, ou autre document officiel", max_length=50, null=True, verbose_name="Numéro de pièce d'identité")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/', verbose_name='Photo')),
                ('consentement_rgpd', models.BooleanField(default=False, help_text="L'utilisateur a consenti au traitement de ses données personnelles", verbose_name='Consentement RGPD')),
                ('date_consentement', models.DateTimeField(blank=True, null=True, verbose_name='Date du consentement')),
                ('created_by', models.CharField(help_text="Nom de l'opérateur ayant créé la fiche", max_length=100, verbose_name='Créé par')),
                ('notes', models.TextField(blank=True, help_text="Notes internes (non affichées à l'utilisateur)", null=True, verbose_name='Notes')),
                ('nombre_sessions_total', models.IntegerField(default=0, verbose_name='Nombre de sessions total')),
                ('derniere_session', models.DateTimeField(blank=True, null=True, verbose_name='Dernière session')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='utilisateur_nom_d68673_idx'), models.Index(fields=['email'], name='utilisateur_email_1cb90f_idx'), models.Index(fields=['carte_identite'], name='utilisateur_carte_i_faa6ab_idx'), models.Index(fields=['-created_at'], name='utilisateur_created_907f18_idx')],
            },
        ),
    ]
