# Generated by Django 5.0.1 on 2025-12-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_guest',
            field=models.BooleanField(default=False, help_text="True si c'est un utilisateur invité anonyme", verbose_name='Utilisateur invité'),
        ),
    ]
