# Generated by Django 4.2.26 on 2025-11-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation_utilisateur', 'Création utilisateur'), ('modification_utilisateur', 'Modification utilisateur'), ('suppression_utilisateur', 'Suppression utilisateur'), ('generation_code', 'Génération code'), ('demarrage_session', 'Démarrage session'), ('ajout_temps', 'Ajout de temps'), ('fermeture', 'Fermeture session'), ('expiration', 'Expiration session'), ('suspension', 'Suspension session'), ('reprise', 'Reprise session'), ('connexion_poste', 'Connexion poste client'), ('deconnexion_poste', 'Déconnexion poste client'), ('changement_statut_poste', 'Changement statut poste'), ('connexion_operateur', 'Connexion opérateur'), ('deconnexion_operateur', 'Déconnexion opérateur'), ('erreur', 'Erreur système'), ('warning', 'Avertissement'), ('info', 'Information')], db_index=True, max_length=50, verbose_name='Action')),
                ('operateur', models.CharField(blank=True, help_text="Nom de l'opérateur ou 'system' pour les actions automatiques", max_length=100, null=True, verbose_name='Opérateur')),
                ('details', models.TextField(help_text="Description détaillée de l'action", verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP de l'utilisateur ou du poste ayant effectué l'action", null=True, protocol='IPv4', verbose_name='Adresse IP')),
                ('metadata', models.JSONField(blank=True, help_text='Données supplémentaires au format JSON', null=True, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sessions.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='logs_created_dfc914_idx'), models.Index(fields=['action'], name='logs_action_68aa90_idx'), models.Index(fields=['session'], name='logs_session_e7d78a_idx'), models.Index(fields=['operateur'], name='logs_operate_a8c076_idx'), models.Index(fields=['created_at', 'action'], name='logs_created_54a7e0_idx')],
            },
        ),
    ]
