#!/bin/bash
set -e

echo "🚀 Création de la structure du projet Poste Public Manager..."

# Répertoires principaux
dirs=(
  "ansible/inventory/group_vars"
  "ansible/playbooks"
  "ansible/roles/common/tasks"
  "ansible/roles/common/templates"
  "ansible/roles/common/files"
  "ansible/roles/docker/tasks"
  "ansible/roles/docker/templates"
  "ansible/roles/network/tasks"
  "ansible/roles/network/templates"
  "ansible/roles/dnsmasq/tasks"
  "ansible/roles/dnsmasq/templates"
  "ansible/roles/dnsmasq/files"
  "ansible/roles/pxe-server/tasks"
  "ansible/roles/pxe-server/files"
  "ansible/roles/live-image/tasks"
  "ansible/roles/live-image/templates"
  "ansible/roles/services/tasks"
  "ansible/roles/services/templates"
  "backend/config/settings"
  "backend/apps/core/management/commands"
  "backend/apps/utilisateurs/management/commands"
  "backend/apps/postes/management/commands"
  "backend/apps/sessions/management/commands"
  "backend/apps/logs/management/commands"
  "backend/apps/auth"
  "backend/static"
  "backend/media/photos"
  "backend/templates"
  "backend/tests"
  "backend/requirements"
  "frontend/src/assets/images"
  "frontend/src/assets/styles"
  "frontend/src/components/common"
  "frontend/src/components/dashboard"
  "frontend/src/components/utilisateurs"
  "frontend/src/components/sessions"
  "frontend/src/components/postes"
  "frontend/src/components/logs"
  "frontend/src/views"
  "frontend/src/router"
  "frontend/src/stores"
  "frontend/src/services"
  "frontend/src/utils"
  "frontend/public"
  "client/systemd"
  "client-windows/ui/resources/icons"
  "client-windows/core"
  "client-windows/utils"
  "live-image/config/package-lists"
  "live-image/config/includes.chroot/etc/skel"
  "live-image/config/includes.chroot/etc/systemd/system"
  "live-image/config/includes.chroot/etc/NetworkManager"
  "live-image/config/includes.chroot/usr/local/bin"
  "live-image/config/hooks/live"
  "live-image/config/archives"
  "live-image/auto"
  "docker/traefik/dynamic"
  "docker/nginx/sites-enabled"
  "docker/pihole"
  "docker/dnsmasq"
  "docker/postgres"
  "scripts"
  "docs"
)

for dir in "${dirs[@]}"; do
  mkdir -p "$dir"
done

echo "✅ Structure créée avec succès!"
echo ""
echo "📁 Arborescence principale:"
ls -d */ 2>/dev/null | head -10

