# Generated by Django 4.2.26 on 2025-11-19 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0001_initial'),
        ('postes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code_acces', models.CharField(db_index=True, help_text='Code unique pour démarrer la session', max_length=10, unique=True, verbose_name="Code d'accès")),
                ('duree_initiale', models.IntegerField(help_text='Durée initiale en secondes (minimum 60s = 1min)', validators=[django.core.validators.MinValueValidator(60)], verbose_name='Durée initiale')),
                ('temps_restant', models.IntegerField(help_text='Temps restant en secondes', verbose_name='Temps restant')),
                ('temps_ajoute', models.IntegerField(default=0, help_text='Temps total ajouté en secondes', verbose_name='Temps ajouté')),
                ('debut_session', models.DateTimeField(blank=True, null=True, verbose_name='Début de session')),
                ('fin_session', models.DateTimeField(blank=True, null=True, verbose_name='Fin de session')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('active', 'Active'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue'), ('expiree', 'Expirée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('operateur', models.CharField(help_text="Nom de l'opérateur ayant créé la session", max_length=100, verbose_name='Opérateur')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='postes.poste', verbose_name='Poste')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='utilisateurs.utilisateur', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut'], name='sessions_statut_a3179f_idx'), models.Index(fields=['code_acces'], name='sessions_code_ac_ed4ddd_idx'), models.Index(fields=['utilisateur', 'poste'], name='sessions_utilisa_725df6_idx'), models.Index(fields=['debut_session'], name='sessions_debut_s_ba5c58_idx'), models.Index(fields=['-created_at'], name='sessions_created_eb29b2_idx')],
            },
        ),
    ]
