# Generated by Django 4.2.26 on 2025-11-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(help_text='Ex: Poste-01, PC-Public-A, etc.', max_length=50, unique=True, verbose_name='Nom du poste')),
                ('ip_address', models.GenericIPAddressField(help_text='Adresse IP du poste (ex: 192.168.1.100)', protocol='IPv4', verbose_name='Adresse IP')),
                ('mac_address', models.CharField(blank=True, help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, null=True, verbose_name='Adresse MAC')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('hors_ligne', 'Hors ligne'), ('maintenance', 'En maintenance')], default='disponible', max_length=20, verbose_name='Statut')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('version_client', models.CharField(blank=True, help_text='Version du logiciel client installé', max_length=50, null=True, verbose_name='Version du client')),
                ('emplacement', models.CharField(blank=True, help_text='Ex: Salle principale, Bureau 2, etc.', max_length=100, null=True, verbose_name='Emplacement physique')),
                ('notes', models.TextField(blank=True, help_text='Notes techniques ou remarques', null=True, verbose_name='Notes')),
                ('nombre_sessions_total', models.IntegerField(default=0, verbose_name='Nombre de sessions total')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'db_table': 'postes',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['statut'], name='postes_statut_449bd2_idx'), models.Index(fields=['ip_address'], name='postes_ip_addr_041b60_idx'), models.Index(fields=['mac_address'], name='postes_mac_add_54f312_idx')],
            },
        ),
    ]
