# Generated by Django 5.0.1 on 2025-12-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='certificate_cn',
            field=models.CharField(blank=True, help_text='Common Name du certificat (auto-généré)', max_length=100, null=True, unique=True, verbose_name='CN du certificat'),
        ),
        migrations.AddField(
            model_name='poste',
            name='certificate_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificat expire le'),
        ),
        migrations.AddField(
            model_name='poste',
            name='certificate_fingerprint',
            field=models.CharField(blank=True, help_text='SHA256 fingerprint du certificat', max_length=64, null=True, verbose_name='Empreinte certificat'),
        ),
        migrations.AddField(
            model_name='poste',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificat délivré le'),
        ),
        migrations.AddField(
            model_name='poste',
            name='is_certificate_revoked',
            field=models.BooleanField(default=False, verbose_name='Certificat révoqué'),
        ),
        migrations.AddField(
            model_name='poste',
            name='registration_token',
            field=models.CharField(blank=True, help_text="Token temporaire pour l'enregistrement du client", max_length=64, null=True, verbose_name="Token d'enregistrement"),
        ),
        migrations.AddField(
            model_name='poste',
            name='registration_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration du token'),
        ),
    ]
