# Generated by Django 5.0.1 on 2025-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postes', '0002_add_certificate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='discovered_at',
            field=models.DateTimeField(blank=True, help_text='Date de la première découverte automatique', null=True, verbose_name='Date de découverte'),
        ),
        migrations.AddField(
            model_name='poste',
            name='discovered_hostname',
            field=models.CharField(blank=True, help_text='Hostname reporté par le client lors de la découverte', max_length=255, null=True, verbose_name='Hostname découvert'),
        ),
        migrations.AddField(
            model_name='poste',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='poste',
            name='validated_by',
            field=models.CharField(blank=True, help_text='Utilisateur ayant validé ce poste', max_length=100, null=True, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, null=True, unique=True, verbose_name='Adresse MAC'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='statut',
            field=models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('disponible', 'Disponible'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('hors_ligne', 'Hors ligne'), ('maintenance', 'En maintenance')], default='disponible', max_length=25, verbose_name='Statut'),
        ),
    ]
